# Generated by Django 3.1.7 on 2021-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210426_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessphoto',
            name='path',
            field=models.FileField(upload_to='media/business_photos/'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='path',
            field=models.FileField(upload_to='media/event_photos/'),
        ),
    ]
