# Generated by Django 3.2 on 2021-04-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_type2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Type2',
        ),
    ]
