# Generated by Django 3.2 on 2021-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210427_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profilePhoto',
            field=models.FileField(default='business_photos/userDefault.png', upload_to='business_photos/'),
        ),
    ]
